FROM golang:1.8.3

RUN mkdir -p /go/src/github.com/gianarb/orbiter
ADD . /go/src/github.com/gianarb/orbiter/
WORKDIR /go/src/github.com/gianarb/orbiter
RUN go build -o orbiter 
RUN mv ./orbiter /bin/orbiter


ENTRYPOINT ["orbiter"]
CMD ["orbiter", "daemon"]
