
## Gopkg.toml example (these lines may be deleted)

## "metadata" defines metadata about the project that could be used by other independent
## systems. The metadata defined here will be ignored by dep.
# [metadata]
# key1 = "value that convey data to other systems"
# system1-data = "value that is used by a system"
# system2-data = "value that is used by another system"

## "required" lists a set of packages (not projects) that must be included in
## Gopkg.lock. This list is merged with the set of packages imported by the current
## project. Use it when your project needs a package it doesn't explicitly import -
## including "main" packages.
# required = ["github.com/user/thing/cmd/thing"]

## "ignored" lists a set of packages (not projects) that are ignored when
## dep statically analyzes source code. Ignored packages can be in this project,
## or in a dependency.
# ignored = ["github.com/user/project/badpkg"]

## Constraints are rules for how directly imported projects
## may be incorporated into the depgraph. They are respected by
## dep whether coming from the Gopkg.toml of the current project or a dependency.
# [[constraint]]
## Required: the root import path of the project being constrained.
# name = "github.com/user/project"
#
## Recommended: the version constraint to enforce for the project.
## Only one of "branch", "version" or "revision" can be specified.
# version = "1.0.0"
# branch = "master"
# revision = "abc123"
#
## Optional: an alternate location (URL or import path) for the project's source.
# source = "https://github.com/myfork/package.git"
#
## "metadata" defines metadata about the dependency or override that could be used
## by other independent systems. The metadata defined here will be ignored by dep.
# [metadata]
# key1 = "value that convey data to other systems"
# system1-data = "value that is used by a system"
# system2-data = "value that is used by another system"

## Overrides have the same structure as [[constraint]], but supersede all
## [[constraint]] declarations from all projects. Only [[override]] from
## the current project's are applied.
##
## Overrides are a sledgehammer. Use them only as a last resort.
# [[override]]
## Required: the root import path of the project being constrained.
# name = "github.com/user/project"
#
## Optional: specifying a version constraint override will cause all other
## constraints on this project to be ignored; only the overridden constraint
## need be satisfied.
## Again, only one of "branch", "version" or "revision" can be specified.
# version = "1.0.0"
# branch = "master"
# revision = "abc123"
#
## Optional: specifying an alternate source location as an override will
## enforce that the alternate location is used for that project, regardless of
## what source location any dependent projects specify.
# source = "https://github.com/myfork/package.git"

[[constraint]]
  name = "github.com/Microsoft/go-winio"
  version = "v0.3.8"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  branch = "master"

[[constraint]]
  name = "github.com/go-yaml/yaml"
  branch = "v2"

[[constraint]]
  name = "github.com/gorilla/mux"
  branch = "master"


[[constraint]]
  name = "github.com/mitchellh/cli"
  branch = "master"

[[constraint]]
  name = "github.com/armon/go-radix"
  revision = "4239b77079c7b5d1243b7b4736304ce8ddb6f0f2"

[[constraint]]
  name = "github.com/bgentry/speakeasy"
  revision = "675b82c74c0ed12283ee81ba8a534c8982c07b85"

[[constraint]]
  name = "github.com/digitalocean/godo"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/docker/distribution"
  version = "v2.6.0"

[[constraint]]
  name = "github.com/docker/docker"
  version = "v1.13.1"

[[constraint]]
  name = "github.com/docker/go-units"
  version = "v0.3.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "69b215d01a5606c843240eab4937eab3acee6530"

[[constraint]]
  name = "github.com/google/go-querystring"
  revision = "53e6ce116135b80d037921a7fdd5138cf32d7a8a"

[[constraint]]
  name = "github.com/gorilla/context"
  version = "v1.1"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/opencontainers/runc"
  version = "v0.1.1"


[[constraint]]
  name = "github.com/pkg/errors"
  version = "v0.8.0"


[[constraint]]
  name = "github.com/tent/http-link-go"
  branch = "master"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"


[[constraint]]
  name = "golang.org/x/oauth2"
  branch = "master"


[[constraint]]
  name = "golang.org/x/sys"
  branch = "master"


[[constraint]]
  name = "google.golang.org/appengine"
  version = "v1.0.0"